### ISSUE TITLE
Current backwards compatability checks are preventing dependencies from being updated.

### ISSUE THREAD

**Issue by lukemarkwordtlibertyits** [auth0/node-samlp#110]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

> Provide a clear and concise description of the issue, including what you expected to happen.

There has been a request to update the node-saml dependency to its current version. [issue](https://github.com/auth0/node-samlp/issues/107). I has submitted a [PR](https://github.com/auth0/node-samlp/pull/109) for this, but the CI is failing. See [here](https://travis-ci.org/github/auth0/node-samlp/builds/748802099). The failure is due to another Auth0 dependency, [xml-encryption](https://github.com/auth0/node-xml-encryption). This dependency uses default argument values, which are not supported until Node 6. The backwards compatibility checks for this repository checks from Node v4.8.5 onward. The backwards compatibility checks for the xml-encryption repository checks from Node 8 onward. 

Since this organization own the node-saml, node-samlp and xml-encryption repository and the node-samlp project utilizes both the node-saml and xml-encryption dependency, it would be helpful for them to have the same backwards compatibility standards, so all repositories can utilize the latest version of each dependency. 

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

```
git checkout lukemarkwordtlibertyits:master
nvm use v4.8.5
npm test
```

[CLI Failure](https://travis-ci.org/github/auth0/node-samlp/jobs/748802100#L240)

### Environment

> Please provide the following:

- **Version of this library used:**
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**
Node Version 4.8.5

**Comment by tomauth0** [comment]
Hi @lukemarkwordtlibertyits - as mentioned on the PR comment, the CI for this repo has been switched to GH Actions, and older node versions have been removed from those builds.  

Thanks again for your suggestions - hopefully these changes make contributions easier.
Tom
