### ISSUE TITLE
SAML Response without InResponseTo

### ISSUE THREAD

**Issue by paulocheque** [auth0/node-samlp#58]
I configured Auth0 as a Identity Provider and it is generating the `samlp:Response` XML with this `InResponseTo` parameter. But this is incompatible with my Service Provider, so I would like to generate the XML without it. 

This attribute appears in the root node and in the `saml:SubjectConfirmationData` node.

How can I do that? Is this library related to the internal Auth0 SAML system?

Ref: https://github.com/auth0/node-samlp/issues/39

Thanks in advance

**Comment by paulocheque** [comment]
Answer, just for reference: https://www.ca.com/us/services-support/ca-support/ca-support-online/knowledge-base-articles.tec1653345.html

**Comment by awesomehimanshu** [comment]
No such link exist . Can you add answer.
