### ISSUE TITLE
ReDOS (NSP 532)

### ISSUE THREAD

**Issue by alexlapinski** [auth0/node-samlp#64]
Hi, we currently make use of your package, and I noticed an open NSP issue regarding moment in the lower package (node-saml) that is still using an unpatched version of moment.

I was wondering if you would be able to update the dependency once your other package (saml) has been patched.

related ticket: https://github.com/auth0/node-saml/issues/38

**Comment by luuuis** [comment]
Fixed by https://github.com/auth0/node-samlp/commit/16c4a36df12d1473c79e1435a223ac587c3e93f7.
