### ISSUE TITLE
Cannot sign the assertion

### ISSUE THREAD

**Issue by GreenGremlin** [auth0/node-samlp#69]
[According to SAML spec](http://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-tech-overview-2.0.html#4.6.Security%20in%20SAML|outline), the SAML response should always be signed and the SAML assertion can optionally be signed. `samlp.auth` currently only allows for the response to be signed, and it defaults to not signing it.

### Desired behavior

The response should always be signed, and there should be an option added `signAssertion` to sign the assertion as well.

``` javascript
samlp.auth({
    ...,
    signAssertion: true,
});
```

The above code should result in a SAML response with both a signed response and a signed assertion. The `signResponse` option should default to true and `signAssertion` should default to false.

**Comment by LoneRifle** [comment]
I've fixed this and released 1.0.0 of xml-crypto, and will send in a PR

**Comment by mgloystein** [comment]
Any plans to support asymmetric assertion encryption?

**Comment by luuuis** [comment]
[samlp@4.0.0](https://www.npmjs.com/package/samlp/v/4.0.0) adds a `signAssertion` option in addition to the already available `signResponse`.

Fixed by https://github.com/auth0/node-samlp/pull/104
