### ISSUE TITLE
Hoe can I specify the NameIDFormat

### ISSUE THREAD

**Issue by jerryOkafor** [auth0/node-samlp#84]
Please I have not seen where I can specify a different NameIDFormat other than `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress`.

I need to use `urn:oasis:names:tc:SAML:1.1:nameid-format:phoneNumber`

Thanks.

**Comment by avlapeto** [comment]
You can use `nameIdentifierFormat`.
